### ISSUE TITLE
Double definition of OnLeftDClick breaks mouse click zooming

### ISSUE THREAD

**Issue by ab3nd** [rzzzwilson/pySlip#67]
The event handler OnLeftDClick is defined twice in pyslip.py, once at lines 1993-2017 and again at lines 2091-1099. The second declaration shadows the first, and also doesn't do anything, so zooming in and out by double clicking doesn't work. 

Removing it appears to fix zooming.

**Comment by rzzzwilson** [comment]
You are quite correct.  Sorry about that.  I have removed the extra definition at lines 1099-2091.  I *have not* tested the change because I test on MacOS and Linux, neither of which want to easily install wxpython, and I'm not too interested in trying to figure out why wxpython won't work in a virtual environment.

I'll push the change up to PyPi soon.
